/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMailRouteImport } from './routes/api/mail'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAccountRouteImport } from './routes/api/account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailRoute = ApiMailRouteImport.update({
  id: '/api/mail',
  path: '/api/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRoute
  '/api/mail': typeof ApiMailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRoute
  '/api/mail': typeof ApiMailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/account': typeof ApiAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRoute
  '/api/mail': typeof ApiMailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/account' | '/api/chat' | '/api/files' | '/api/mail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/account' | '/api/chat' | '/api/files' | '/api/mail'
  id:
    | '__root__'
    | '/'
    | '/api/account'
    | '/api/chat'
    | '/api/files'
    | '/api/mail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiMailRoute: typeof ApiMailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail': {
      id: '/api/mail'
      path: '/api/mail'
      fullPath: '/api/mail'
      preLoaderRoute: typeof ApiMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiMailRoute: ApiMailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
